steps:
- name: 'gcr.io/cloud-builders/docker'
  entrypoint: 'bash'
  args: ['-c', 'docker pull gcr.io/$PROJECT_ID/ch-github-events:latest || exit 0']
- name: 'gcr.io/cloud-builders/docker'
  args: [
            'build',
            '-t', 'gcr.io/$PROJECT_ID/ch-github-events:latest',
            '--cache-from', 'gcr.io/$PROJECT_ID/ch-github-events:latest',
            '.'
        ]
# Push the container image to Container Registry
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'gcr.io/$PROJECT_ID/ch-github-events:latest']
# Deploy container image to Cloud Run
- name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
  entrypoint: gcloud
  args: ['run', 'jobs', 'deploy', 'ch-github-events', '--image', 'gcr.io/$PROJECT_ID/ch-github-events:latest', '--region', 'us-central1']
images: ['gcr.io/$PROJECT_ID/ch-github-events:latest']
